name: Sync from Gitee
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 关键：给推送代码的权限
    steps:
      - name: Sync from Gitee to GitHub
        run: |
          git clone --bare https://gitee.com/tengxiaobao/tvbox-source-aggregator.git upstream
          cd upstream
          git push --mirror https://github.com/${{ github.repository }}.git
