name: Sync from Gitee
on:
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: '0 * * * *'  # 每小时自动同步一次

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取上游仓库并推送到 GitHub
        run: |
          git clone --bare https://gitee.com/tengxiaobao/tvbox-source-aggregator.git upstream
          cd upstream
          git push --mirror https://github.com/${{ github.repository }}.git
